//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlashcardMaker.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Users\\Mosarvit\\Documents\\SharedFolder\\subtitles\\Media")]
        public string UsersMediaFolder {
            get {
                return ((string)(this["UsersMediaFolder"]));
            }
            set {
                this["UsersMediaFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int ExtraPaddingCut {
            get {
                return ((int)(this["ExtraPaddingCut"]));
            }
            set {
                this["ExtraPaddingCut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ricky.heliohost.org")]
        public string HostName {
            get {
                return ((string)(this["HostName"]));
            }
            set {
                this["HostName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mosar")]
        public string UserName {
            get {
                return ((string)(this["UserName"]));
            }
            set {
                this["UserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fahrenheit")]
        public string Password {
            get {
                return ((string)(this["Password"]));
            }
            set {
                this["Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Users\\Mosarvit\\Documents\\MediaFiles")]
        public string ApplicationsMediaFolder {
            get {
                return ((string)(this["ApplicationsMediaFolder"]));
            }
            set {
                this["ApplicationsMediaFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ftp://mosar.heliohost.org/mediafiles")]
        public string FtpMediaFolder {
            get {
                return ((string)(this["FtpMediaFolder"]));
            }
            set {
                this["FtpMediaFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DEBUG_MAX_CREATE_SUBTITLE_LINEPACKS {
            get {
                return ((int)(this["DEBUG_MAX_CREATE_SUBTITLE_LINEPACKS"]));
            }
            set {
                this["DEBUG_MAX_CREATE_SUBTITLE_LINEPACKS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DEBUG_MAX_SORT_SUBTITLE_LINEPACKS {
            get {
                return ((int)(this["DEBUG_MAX_SORT_SUBTITLE_LINEPACKS"]));
            }
            set {
                this["DEBUG_MAX_SORT_SUBTITLE_LINEPACKS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DEBUG_MAX_CREATE_MEDIA_FILES {
            get {
                return ((int)(this["DEBUG_MAX_CREATE_MEDIA_FILES"]));
            }
            set {
                this["DEBUG_MAX_CREATE_MEDIA_FILES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DEBUG_MAX_CREATE_FLASHCARDS {
            get {
                return ((int)(this["DEBUG_MAX_CREATE_FLASHCARDS"]));
            }
            set {
                this["DEBUG_MAX_CREATE_FLASHCARDS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DEBUG_ONLY_CREATE_FLASHCARDS_WITH_MEDIAFILES {
            get {
                return ((bool)(this["DEBUG_ONLY_CREATE_FLASHCARDS_WITH_MEDIAFILES"]));
            }
            set {
                this["DEBUG_ONLY_CREATE_FLASHCARDS_WITH_MEDIAFILES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DEBUG_MAX_CCS_TO_LOAD {
            get {
                return ((int)(this["DEBUG_MAX_CCS_TO_LOAD"]));
            }
            set {
                this["DEBUG_MAX_CCS_TO_LOAD"] = value;
            }
        }
    }
}
